### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by dblessing** [mwrock/kitchen-vsphere#5]
What's the status of this project? Is it considered stable enough to use for day-to-day kitchen testing? If so, it would be great to have a stable gem release so `--pre` isn't necessary to install.

**Comment by dblessing** [comment]
I see your comment in the other issue about not actively maintaining this anymore. Thanks!

**Comment by mwrock** [comment]
I went ahead and pushed a stable 0.2.0 gem

**Comment by zarry** [comment]
@dblessing Just to piggy back on this, I have been using the gem daily for a month or two now.  Works great!  @mwrock I appreciate publishing the stable gem!  I was actually coming back to let you know its been working well and requesting the publish.

Thanks!

**Comment by mwrock** [comment]
Great to hear! Really hope to one day get the driver I do support at work open sourced.
