### ISSUE TITLE
VM Base Path

### ISSUE THREAD

**Issue by james-s-nduka** [mwrock/kitchen-vsphere#7]
Is there a way to explicitly state the vm_base_path (directory) to where you want kitchen to create the new vsphere machine? The vagrant-vSphere plugin handles this quite well. By default the vm is created in the same directory as its template :(

**Comment by mwrock** [comment]
Use the `dest_folder` option. Been a while since I have used this driver but that option worked well for me.

**Comment by james-s-nduka** [comment]
That works - great. How can I easily view all the options available for this driver? Great work on this overall.

**Comment by mwrock** [comment]
The `server_create` hash is fed directly to the fog API's `::Fog::Compute::vm_clone` method. So it really depends on the fog gem version you are using. Here is a link to the current version with a list of the supported options:

https://github.com/fog/fog/blob/master/lib/fog/vsphere/requests/compute/vm_clone.rb#L33
